apiVersion: tekton.dev/v1alpha1
kind: Task
metadata:
  name: deploy-reviews-app
spec:
  inputs:
    resources:
      - name: image
        type: image
    params:
      - name: APP_NAME
        description: The name of the application
        default: 'reviews'
        type: string
      - name: APP_VERSION
        description: The version of the application
        default: '1.0'
        type: string
      - name: DEPLOY_PROJECT
        description: The project where you deploy the app
        default: 'env-dev'
        type: string

  steps:
      - name: create-app
        image: quay.io/openshift/origin-cli:latest
        workingDir: /workspace/source
        command: ["/bin/bash", "-c"]
        args:
          - |-
            oc get deployment $(inputs.params.APP_NAME) -n $(inputs.params.DEPLOY_PROJECT)
            if [[ $? -ne 0 ]]
            then
                oc new-app -i $(inputs.params.APP_NAME) -n $(inputs.params.DEPLOY_PROJECT)
            else
                echo "Application already exists."
            fi
      - name: expose-app
        image: quay.io/openshift/origin-cli:latest
        workingDir: /workspace/source
        command: ["/bin/bash", "-c"]
        args:
          - |-
            oc get route $(inputs.params.APP_NAME) -n $(inputs.params.DEPLOY_PROJECT)
            if [[ $? -ne 0 ]]
            then
                oc expose svc/$(inputs.params.APP_NAME) -n $(inputs.params.DEPLOY_PROJECT)
            else
                echo "Application is already exposed."
            fi
      - name: set-app-labels
        image: quay.io/openshift/origin-cli:latest
        workingDir: /workspace/source
        command: ["/bin/bash", "-c"]
        args:
          - |-
            oc label deployment/$(inputs.params.APP_NAME) app.kubernetes.io/name=reviews --overwrite -n $(inputs.params.DEPLOY_PROJECT)
            oc label deployment/$(inputs.params.APP_NAME) app.version=$(inputs.params.APP_VERSION) --overwrite -n $(inputs.params.DEPLOY_PROJECT)
      - name: describe-app-triggers
        image: quay.io/openshift/origin-cli:latest
        workingDir: /workspace/source
        command: ["/bin/bash", "-c"]
        args:
          - |-
            oc set triggers deployment/$(inputs.params.APP_NAME) -n $(inputs.params.DEPLOY_PROJECT)