apiVersion: tekton.dev/v1alpha1
kind: Pipeline
metadata:
  name: productpage-pipeline
spec:
  resources:
    - name: bookinfo-git
      type: git
    - name: productpage-image-dev
      type: image

  params:
    - name: APP_NAME
      description: The name of the application
      default: 'productpage-tekton'      
    - name: APP_VERSION
      description: The version of the application
      default: '1.0'      
    - name: DEPLOY_PROJECT
      description: The project where you deploy the app
      default: 'bookinfo-dev'

  tasks:
  - name: build
    taskRef:
      name: productpage-build-push

    resources:       
      inputs:
        - name: source
          resource: bookinfo-git
      outputs:
        - name: image
          resource: productpage-image-dev
  - name: deploy
    taskRef:
      name: deploy-productpage-app
    runAfter:
      - build
    params:
        - name: APP_NAME
          value: "$(params.APP_NAME)"
        - name: APP_VERSION
          value: "$(params.APP_VERSION)"  
        - name: DEPLOY_PROJECT
          value: "$(params.DEPLOY_PROJECT)"    
    resources:
      inputs:
        - name: image
          resource: productpage-image-dev
