apiVersion: tekton.dev/v1alpha1
kind: Pipeline
metadata:
  name: details
  -pipeline
spec:
  resources:
    - name: bookinfo-git
      type: git
    - name: details
    -image-dev
      type: image

  params:
    - name: APP_NAME
      description: The name of the application
      default: 'details
      -tekton'      
    - name: APP_VERSION
      description: The version of the application
      default: '1.0'      
    - name: DEPLOY_PROJECT
      description: The project where you deploy the app
      default: 'bookinfo-dev'

  tasks:
  - name: build
    taskRef:
      name: details
      -build-push

    resources:       
      inputs:
        - name: source
          resource: bookinfo-git
      outputs:
        - name: image
          resource: details
          -image-dev
  - name: deploy
    taskRef:
      name: deploy-details
      -app
    runAfter:
      - build
    params:
        - name: APP_NAME
          value: "$(params.APP_NAME)"
        - name: APP_VERSION
          value: "$(params.APP_VERSION)"  
        - name: DEPLOY_PROJECT
          value: "$(params.DEPLOY_PROJECT)"    
    resources:
      inputs:
        - name: image
          resource: details
          -image-dev
