apiVersion: tekton.dev/v1alpha1
kind: Task
metadata:
  name: details-build-push
spec:
  inputs:
    resources:
      - name: source
        type: git
    params:
      - name: VERSION
        description: The version of the nodejs
        default: 'latest'
        type: string
      - name: PATH_CONTEXT
        description: The location of the path to run s2i from.
        default: "src/details"
        type: string
      - name: TLSVERIFY
        description: Verify the TLS on the registry endpoint (for push/pull to a non-TLS registry)
        default: "false"
        type: string
  outputs:
    resources:
      - name: image
        type: image
  steps:
    - name: build
      image: quay.io/buildah/stable:v1.11.0
      workingdir: /workspace/source/$(inputs.params.PATH_CONTEXT)
      command: ['buildah', 'bud', '--tls-verify=$(inputs.params.TLSVERIFY)', '--layers', '-f', 'Dockerfile', '-t', '$(outputs.resources.image.url)', '.']
      volumeMounts:
        - name: varlibcontainers
          mountPath: /var/lib/containers
      securityContext:
        privileged: true
    - name: push
      image: quay.io/buildah/stable:v1.11.0
      command: ['buildah', 'push', '--tls-verify=$(inputs.params.TLSVERIFY)', '$(outputs.resources.image.url)', 'docker://$(outputs.resources.image.url)']
      volumeMounts:
        - name: varlibcontainers
          mountPath: /var/lib/containers
      securityContext:
        privileged: true
  volumes:
    - name: varlibcontainers
      emptyDir: {}
